import clippers from "../images/clipper.jpg";

export const products = [
	{
		id: 1,
		name: "Barbing Chair",
		needs: 2,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 2,
		name: "Sterilizing Machine",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 3,
		name: "Hot Water Machine",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 4,
		name: "Customer Waiting Chairs",
		needs: "2 Long Chairs",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 5,
		name: "Standard Hair Dryer",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 6,
		name: "Standard Hair Washer & Tap",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 7,
		name: "Air Conditioner (AC)",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 8,
		name: "Generator ",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 9,
		name: "Standing Fan",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 10,
		name: "Hair Tonging Stove (SET)",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 11,
		name: "Straigheners",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 12,
		name: "Trolley",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 13,
		name: "Hand Dryer",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 14,
		name: "TV",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 15,
		name: "Sound System",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 16,
		name: "Mirror",
		needs: "Depend on the size of the Work Space",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 17,
		name: "Clippers",
		needs: 4,
		price: 0,
		image: clippers,
		totalPrice: 0,
	},
	{
		id: 18,
		name: "Clipper Out-liner",
		needs: 2,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 19,
		name: "Clipper Oil",
		needs: 2,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 20,
		name: "Clipper Brush",
		needs: 4,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 21,
		name: "Aftershave",
		needs: "Pack",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 22,
		name: "Hair Spray",
		needs: "Different Types & Qualities",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 23,
		name: "Apron",
		needs: "5 Pron for Haircults & 1 for Hair Dye ",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 24,
		name: "Hair Brush",
		needs: 4,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 25,
		name: "Hair Dusting Brush",
		needs: 3,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 26,
		name: "Powder",
		needs: 1,
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 27,
		name: "Clipper Blade & Linner Blades",
		needs: "pack",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 28,
		name: "Disposable Neck Tissue ",
		needs: "Pack",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 29,
		name: "Hair Spray",
		needs: "pack",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
	{
		id: 30,
		name: "Combs",
		needs: "Different Types & Qualities",
		price: 0,
		image: "https://via.placeholder.com/150",
		totalPrice: 0,
	},
];
